server:
  port: 8083
springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/acquirerdb
    username: root
    password: Gringotts
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
  security:
    user:
      name: username
      password: secret
      roles: USER
jwt:
  secret: s3cr37F14Ps3cr37F14Ps3cr37F14Ps3cr37F14Ps3cr37F14Ps3cr37F14Ps3cr37F14Ps3cr37F14P
  expirationInSeconds: 1800
